#!/bin/bash
# set $IFS to end-of-line
IFS=`echo -en "\n\b"`
value=0


for var in `find . -name '*.mp3' | sort -n`
do
	value=`expr $value + 1`
	id3v2 -C $var
	id3v2 -T $value $var
	echo "Set Track number to: $value"
done


